flaskblog/posts/forms.py
"""
This module is Post form for post website
"""
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    """
    Form for post site
    """
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/posts/routes.py
"""
This module is route and def for posts
"""
from flask import (render_template, url_for, flash, redirect,
                   request, abort, Blueprint)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm
from flaskblog.side.get_postdates import get_postdates


posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    """
    To post the new blogs on the website
    :return: render create_post.html, title, form, legend, year_dict,
    month_dict, side_posts
    """
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    # to get the number of posts by year and month for submenu
    year_dict, month_dict = get_postdates()
    side_posts = Post.query.order_by(Post.date_posted.desc()).limit(5)
    return render_template('create_post.html', title='New Post', form=form,
                           legend='New Post', year_dict=year_dict,
                           month_dict=month_dict, side_posts=side_posts)


@posts.route('/post/<int:post_id>')
def post(post_id):
    """
    To show the each posts
    :param post_id: unique number by post
    :return: render post.html, title, post, year_dict, month_dict, side_posts
    """
    post = Post.query.get_or_404(post_id)
    year_dict, month_dict = get_postdates()
    side_posts = Post.query.order_by(Post.date_posted.desc()).limit(5)
    return render_template('post.html', title=post.title, post=post,
                           year_dict=year_dict, month_dict=month_dict,
                           side_posts=side_posts)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    """
    To update the post
    :param post_id: unique number by post
    :return: if update post submitted, redirect posts.post and post.id.
    Render the create_post.html, title, from, legend, year_dict, month_dict,
    side_posts
    """
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    # if update post is submitted, redirected to posts.post
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    # To get the title and content to show it on the form
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    year_dict, month_dict = get_postdates()
    side_posts = Post.query.order_by(Post.date_posted.desc()).limit(5)
    return render_template('create_post.html', title='Update Post', form=form,
                           legend='Update Post', year_dict=year_dict,
                           month_dict=month_dict, side_posts=side_posts)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    """
    To delete post by post_id
    :param post_id: unique id by post
    :return: redirect to homepage
    """
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/side/routes.py
"""
This module is routes and def for posts by year and month
"""
import calendar
from datetime import datetime
from flask import render_template, request, Blueprint
from flaskblog.models import Post
from flaskblog.side.get_postdates import get_postdates
import re

side = Blueprint('side', __name__)


@side.route('/archive/<string:filter_date>')
def date_posts(filter_date, start_month=1, end_month=12):
    """
    To show the posts by year and month
    :param filter_date: Input date of year or month to filter
    :param start_month: start_month to filter
    :param end_month: end_month to filter
    :return: render archive.html, posts, year, year_dict, month_dict,
    side_posts
    """
    page = request.args.get('page', 1, type=int)
    # To check if the filter_date is only year
    pattern = r"^\d{4}$"
    # To extract the year for the filter_date with year and month
    pattern_y = r"^\d{4}"
    # To extract the month for the filter_date with year and month
    pattern_m = r"(\d{4})-(\d{1,2})"
    re_pattern = re.compile(pattern)
    re_pattern_y = re.compile(pattern_y)
    re_pattern_m = re.compile(pattern_m)
    if re_pattern.match(filter_date):
        year = filter_date
    else:
        year = re_pattern_y.match(filter_date).group(0)
        start_month = re_pattern_m.match(filter_date).group(2)
        # to filter the month
        end_month = start_month
    # To set the start date for the filter
    start = datetime(year=int(year), month=int(start_month), day=1)
    # To get the last date by month automatically
    last_day = calendar.monthrange(int(year), int(start_month))[1]
    # To set the end date for the filter
    end = datetime(year=int(year), month=int(end_month), day=int(last_day),
                   hour=23, minute=59, second=59)
    posts = Post.query.filter(Post.date_posted <= end)\
        .filter(Post.date_posted >= start)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)

    year_dict, month_dict = get_postdates()
    # if month filter, need to return year and month with year parameter
    if not re_pattern.match(filter_date):
        year = year + "-" + start_month
    side_posts = Post.query.order_by(Post.date_posted.desc()).limit(5)
    return render_template('archive.html', posts=posts, year=year,
                           year_dict=year_dict, month_dict=month_dict,
                           side_posts=side_posts)


"""
from datetime import datetime

start = datetime(year=2016,month=11,day=1)
end = datetime(year=2016,month=11,day=30)

posts = Post.query.filter(Post.date_posted <= end).filter(Post.date_posted 
>= start).all()
"""

flaskblog/users/routes.py
"""
This module is route and def for users
"""
from flask import (render_template, url_for, flash, redirect, request,
                   Blueprint)
from flaskblog import db, bcrypt
from flaskblog.users.forms import (RegistrationForm, LoginForm,
                                   UpdateAccountForm, RequestResetForm,
                                   ResetPasswordForm, UpdatePasswordForm)
from flaskblog.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog.users.utils import save_picture, send_reset_email
from flaskblog.side.get_postdates import get_postdates


"""
As of Apr. 3, 2020, need to use werkzeug==0.16.0 due to the degrade of 1.0.0
"""

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    """
    To register the account for new users
    :return: if authenticated, redirect to homepage.
    if registration is submitted, redirect to login page
    At default, render registration page, title, form, year_dict, month_dict,
    side_posts
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.
                                                        data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data,
                    password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created!', 'success')
        return redirect(url_for('users.login'))
    year_dict, month_dict = get_postdates()
    side_posts = Post.query.order_by(Post.date_posted.desc()).limit(5)
    return render_template('register.html', title='Register', form=form,
                           year_dict=year_dict, month_dict=month_dict,
                           side_posts=side_posts)


@users.route('/login', methods=['GET', 'POST'])
def login():
    """
    To login
    :return: if authenticated, redirected to homepage
    if login form is submitted, and url contains next, redirect to next page,
    otherwise to homepage
    At default render login.html, title, form, year_dict, month_dict,
    side_posts
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # to check the password
        if user and bcrypt.check_password_hash(user.password,
                                               form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('You have been logged in!', 'success')
            return redirect(next_page) if next_page else redirect(
                url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password',
                  'danger')
    year_dict, month_dict = get_postdates()
    side_posts = Post.query.order_by(Post.date_posted.desc()).limit(5)
    return render_template('login.html', title='Login', form=form,
                           year_dict=year_dict, month_dict=month_dict,
                           side_posts=side_posts)


@users.route('/logout')
def logout():
    """
    To logout
    :return: redirect to homepage
    """
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    """
    To update the account information
    :return: if the form is submitted, redirect to users.account, else
    render account.html, title, image_file, form, year_dict, month_dict,
    side_posts with the current user and email filled on the form
    """
    form = UpdateAccountForm()
    if form.validate_on_submit():
        # if the picture is updated
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    # to show the image data on the web site
    image_file = url_for('static',
                         filename='profile_pics/' + current_user.image_file)
    year_dict, month_dict = get_postdates()
    side_posts = Post.query.order_by(Post.date_posted.desc()).limit(5)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form,
                           year_dict=year_dict, month_dict=month_dict,
                           side_posts=side_posts)


@users.route('/user/<string:username>')
def user_posts(username):
    """
    To show the posts by username
    :param username: username registered on the db
    :return: render user_posts.html, posts, user, year_dict, month_dict,
    side_posts
    """
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    year_dict, month_dict = get_postdates()
    side_posts = Post.query.order_by(Post.date_posted.desc()).limit(5)
    return render_template('user_posts.html', posts=posts, user=user,
                           year_dict=year_dict, month_dict=month_dict,
                           side_posts=side_posts)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    """
    TO send the email to reset password
    :return: if authenticated, redirect to homepage
    if form is submitted, redirect to user login
    At default, render reset_request.html, title, form
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # send email
        send_reset_email(user)
        flash('An email has been sent with instructions to reset'
              'your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',
                           title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    """
    To reset the password with token provided by email
    :param token: token generated by get_reset_token and provided by email
    :return: If authenticated, redirect to homepage
    if user is None, redirect to reset_request,
    if form is submitted, redirect to login page
    At default, render reset_token.html, with title and form
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid token or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data). \
                          decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been update! You are now able to log in',
              'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',
                           title='Reset Password', form=form)


@users.route('/account/<string:username>/update_password',
             methods=['GET', 'POST'])
def update_password(username):
    """
    To update the password with authenticated user
    :param username: current login user
    :return: if form is submitted, redirect to users.account
    At default, render update_password.html, title, image_file, form, year_dict
    , month_dict, side_posts
    """
    form = UpdatePasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=username).first()
        if user and bcrypt.check_password_hash(user.password,
                                               form.oldpassword.data):
            hashed_password = bcrypt.generate_password_hash(
                form.password.data).decode('utf-8')
            current_user.password = hashed_password
            db.session.commit()
            flash('Your password has been updated!', 'success')
            return redirect(url_for('users.account'))
    image_file = url_for('static',
                         filename='profile_pics/' + current_user.image_file)
    year_dict, month_dict = get_postdates()
    side_posts = Post.query.order_by(Post.date_posted.desc()).limit(5)
    return render_template('update_password.html', title='Update Password',
                           image_file=image_file, form=form,
                           year_dict=year_dict, month_dict=month_dict,
                           side_posts=side_posts)

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Flask Blog Test Page</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account Info</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span><br/>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                    <small class="text-muted ml-2">
                        <a href="{{ url_for('users.update_password', username=current_user.username) }}">Update Password?</a>
                    </small>
                </div>
            </form>
    </div>
{% endblock content %}

flaskblog/templates/archive.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts in {{year}} ({{ posts.total }})</h1>
    {% for post in posts.items %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" >
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>    
        </div>
    </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('side.date_posts', filter_date=year, page=page_num) }}">{{ page_num }}</a>
        {% else%}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('side.date_posts', filter_date=year, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
        ...
    {% endif %}
    {% endfor %}

{% endblock content %}

flaskblog/templates/archive_menu.html
{% if year_dict and month_dict %}
<div class="archive-module-body">
    <ul class="archive-urllist">
        <div class="archive-recent-posts">
        <h3 class="archive-title">Recent Posts</h3>
        {% for post in side_posts %}
        <article class="media archive-section">
            <img class="rounded-circle archive-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" >
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small>
                </div>
                <h4><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h4>
            </div>
        </article>
        {% endfor %}
        </div>
        <div class="archive-month-archive">
        <h3 class="archive-title">Monthly Archive</h3>
        {% for year, ytotal in year_dict.items() %}
        <li class="archive-module-year" data-year=year>
         <div class="archive-year">
            <span class="archive-module-hide-button">▼</span>
            <span class="archive-module-show-button">▶</span>
         <a class="article-content" href="{{ url_for('side.date_posts', filter_date=year) }}">
             {{ year }} ({{ ytotal }})
          </a>
         </div>
         <div class="archive-month">
         {% for month, mtotal in month_dict.items() %}
            {% if year in month %}
          <ul class="archive-module-months">
              <li class="archive-module-month">
                <a class="article-content" href="{{ url_for('side.date_posts', filter_date=month) }}" >
                    ・{{ month }} ({{ mtotal }})
                </a>
              </li>
          </ul>
            {% endif %}
          </div>
          </div>
        </li>
        {% endfor %}
        {% endfor %}
    </ul>
</div>
{% endif %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" >
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>    
        </div>
    </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else%}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
        ...
    {% endif %}
    {% endfor %}

{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon.ico') }}">
    {% if title %}
        <title>Flask Blog - {{ title}} </title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">  
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">  
            <div class="container">  
                <a class="navbar-brand mr-4" href="/">Flask Blog</a>  
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">  
                    <span class="navbar-toggler-icon"></span>  
                </button>  
                <div class="collapse navbar-collapse" id="navbarToggle">  
                    <div class="navbar-nav mr-auto">  
                        <a class="nav-item nav-link" href="/">Home</a>  
                        <a class="nav-item nav-link" href="/about">About</a>  
                    </div>  
                    <!-- Navbar Right Side -->  
                    <div class="navbar-nav">  
                        {% if current_user.is_authenticated %}
                            <a class="nav-item nav-link" href="{{ url_for('posts.new_post')}}">New Post</a>  
                            <a class="nav-item nav-link" href="{{ url_for('users.account')}}">Account</a>  
                            <a class="nav-item nav-link" href="{{ url_for('users.logout')}}">Logout</a>
                        {% else %}                          
                            <a class="nav-item nav-link" href="{{ url_for('users.login')}}">Login</a>  
                            <a class="nav-item nav-link" href="{{ url_for('users.register')}}">Register</a>
                        {% endif %}  
                    </div>  
                </div>  
            </div>  
        </nav>  
    </header>      
    <main role="main" class="container">  
        <div class="row">  
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                      {{ message }}
                    </div>
                  {% endfor %}
                {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}  
            </div>  
            <div class="col-md-4">
                {% include "archive_menu.html" %}
            </div>  
        </div>  
    </main>      
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="/static/handle_submenu.js"></script>
</body>
</html>

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img"
            src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                        <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                    </div>
                {% endif%}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
  <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
            </div>
        </div>
        </div>
    </div>    
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" >
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d %H:%M:%S') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>    
        </div>
    </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else%}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
        ...
    {% endif %}
    {% endfor %}

{% endblock content %}